services:
  web:
    build: ./image
    image: docker-tt-rss
    volumes:
      - web-data:/srv/www/tt-rss
    container_name: rss_web
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:12-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: rss_db
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

volumes:
  web-data:
  db-data:
